In [1]:
import pandas as pd

In [3]:
products=pd.read_csv('VA-Products.csv')

In [4]:
products.head()

   ProductID      Product Category    Segement  ManufacturerID
0          1  Abbas MA-01      Mix  All Season               1
1          2  Abbas MA-02      Mix  All Season               1
2          3  Abbas MA-03      Mix  All Season               1
3          4  Abbas MA-04      Mix  All Season               1
4          5  Abbas MA-05      Mix  All Season               1

In [6]:
print("Missing values:",products.isnull().sum())

Missing values: ProductID         0
Product           0
Category          0
Segement          0
ManufacturerID    0
dtype: int64

In [7]:
print("Unique values:",products.nunique())

Unique values: ProductID         2412
Product           2172
Category             4
Segement             8
ManufacturerID      14
dtype: int64

In [13]:
print("Distribution based on Segment")
print(products['Segement'].value_counts())
print("Distribution based on Category")
print(products['Category'].value_counts())
print("Distribution based on Manufacturer")
print(products['ManufacturerID'].value_counts())

Distribution based on Segment
Segement
Productivity    598
Convenience     405
Extreme         347
Moderation      306
Regular         262
Select          177
All Season      169
Youth           148
Name: count, dtype: int64
Distribution based on Category
Category
Urban    1320
Rural     743
Mix       201
Youth     148
Name: count, dtype: int64
Distribution based on Manufacturer
ManufacturerID
12    455
8     333
7     302
2     226
1     198
4     194
10    190
5     181
11    137
14     85
6      45
13     38
9      16
3      12
Name: count, dtype: int64

In [14]:
sales=pd.read_csv('VA-Sales.csv')

In [17]:
sales.head()

   ProductID        Date    Zip  Units   Revenue
0       2055    3/4/2011  37387      1  719.1975
1        735  11/26/2007  38834      1  377.9475
2       1212   1/12/2011  40515      1  454.0725
3       2284   7/11/2007  60110      1  330.6975
4       1009   3/21/2008  95534      1  107.5725

In [16]:
print("Missing Values in the sales table:\n",sales.isnull().sum())

Missing Values in the sales table:
 ProductID    0
Date         0
Zip          0
Units        0
Revenue      0
dtype: int64

In [19]:
sales['Date'] = pd.to_datetime(sales['Date'])
sales['Year'] = sales['Date'].dt.year
print("Count of sales in each year: ")
print(sales.groupby('Year').size())

Count of sales in each year:
Year
1999     6471
2000     8690
2001    10886
2002    11822
2003    12765
2004    12950
2005    13216
2006    13113
2007    11860
2008    10784
2009     6611
2010     5461
2011     5417
2012     5542
2013     5337
2014     5985
2015     3087
dtype: int64

In [20]:
sales['Month'] = sales['Date'].dt.month
print("Count of sales in each month: ")
print(sales.groupby('Month').size())

Count of sales in each month:
Month
1      6990
2      9174
3     16066
4     17783
5     18309
6     16575
7     13600
8     12309
9      9911
10     8492
11     8317
12    12471
dtype: int64