In [1]:
import pandas as pd
import os

In [10]:
score_file_path = r"C:\Users\Administrator\a751809\Fid-Case-Study\sentiment_analysis\News_data.csv"
index_data_file_path = r"C:\Users\Administrator\a751809\Fid-Case-Study\data\upload_DJIA_table.csv"
score_df = pd.read_csv(score_file_path)
index_df = pd.read_csv(index_data_file_path)

In [11]:
score_df.drop(index = 0)

,Unnamed: 0,Date,News,Preprocessed Text,Sentiment_score
1,1,2016-07-01,A 117-year-old woman in Mexico City finally re...,117 year old woman Mexico City finally receive...,-0.5994
2,2,2016-07-01,IMF chief backs Athens as permanent Olympic host,IMF chief back Athens permanent olympic host,0.0000
3,3,2016-07-01,"The president of France says if Brexit won, so...",president France say Brexit win Donald Trump,0.5859
4,4,2016-07-01,British Man Who Must Give Police 24 Hours' Not...,british Man Police 24 hour notice sex threaten...,-0.5187
5,5,2016-07-01,100+ Nobel laureates urge Greenpeace to stop o...,100 + Nobel laureate urge Greenpeace stop oppo...,-0.2960
...,...,...,...,...,...
73604,73604,2008-06-08,b'Man goes berzerk in Akihabara and stabs ever...,b'man go berzerk Akihabara stab nearby 6 dead ...,-0.8442
73605,73605,2008-06-08,b'Threat of world AIDS pandemic among heterose...,b'threat world AIDS pandemic heterosexual repo...,0.2023
73606,73606,2008-06-08,b'Angst in Ankara: Turkey Steers into a Danger...,b'Angst Ankara Turkey Steers dangerous Identit...,-0.8020
73607,73607,2008-06-08,"b""UK: Identity cards 'could be used to spy on ...","b""UK identity card spy people new child databa...",-0.5267
73608,73608,2008-06-08,"b'Marriage, they said, was reduced to the stat...",b'Marriage say reduce status commercial transa...,-0.5267

In [12]:
index_df

,Date,Open,High,Low,Close,Volume,Adj Close
0,2016-07-01,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
1,2016-06-30,17712.759766,17930.609375,17711.800781,17929.990234,133030000,17929.990234
2,2016-06-29,17456.019531,17704.509766,17456.019531,17694.679688,106380000,17694.679688
3,2016-06-28,17190.509766,17409.720703,17190.509766,17409.720703,112190000,17409.720703
4,2016-06-27,17355.210938,17355.210938,17063.080078,17140.240234,138740000,17140.240234
...,...,...,...,...,...,...,...
1984,2008-08-14,11532.070312,11718.280273,11450.889648,11615.929688,159790000,11615.929688
1985,2008-08-13,11632.809570,11633.780273,11453.339844,11532.959961,182550000,11532.959961
1986,2008-08-12,11781.700195,11782.349609,11601.519531,11642.469727,173590000,11642.469727
1987,2008-08-11,11729.669922,11867.110352,11675.530273,11782.349609,183190000,11782.349609
1988,2008-08-08,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312

In [20]:
merged_df = pd.merge(score_df,index_df,on='Date',how = 'inner')

In [21]:
merged_df

,Unnamed: 0,Date,News,Preprocessed Text,Sentiment_score,Open,High,Low,Close,Volume,Adj Close
0,1,2016-07-01,A 117-year-old woman in Mexico City finally re...,117 year old woman Mexico City finally receive...,-0.5994,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
1,2,2016-07-01,IMF chief backs Athens as permanent Olympic host,IMF chief back Athens permanent olympic host,0.0000,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
2,3,2016-07-01,"The president of France says if Brexit won, so...",president France say Brexit win Donald Trump,0.5859,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
3,4,2016-07-01,British Man Who Must Give Police 24 Hours' Not...,british Man Police 24 hour notice sex threaten...,-0.5187,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
4,5,2016-07-01,100+ Nobel laureates urge Greenpeace to stop o...,100 + Nobel laureate urge Greenpeace stop oppo...,-0.2960,17924.240234,18002.380859,17916.910156,17949.369141,82160000,17949.369141
...,...,...,...,...,...,...,...,...,...,...,...
49713,72079,2008-08-08,b'Why the Pentagon Thinks Attacking Iran is a ...,b'Why Pentagon think attack Iran Bad Idea News...,-0.7650,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312
49714,72080,2008-08-08,b'Caucasus in crisis: Georgia invades South Os...,b'Caucasus crisis Georgia invade South Ossetia,-0.6249,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312
49715,72081,2008-08-08,b'Indian shoe manufactory - And again in a se...,b'indian shoe manufactory series like work,0.3612,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312
49716,72082,2008-08-08,b'Visitors Suffering from Mental Illnesses Ban...,b'visitor suffer Mental Illnesses ban olympic,-0.8834,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312
49717,72083,2008-08-08,"b""No Help for Mexico's Kidnapping Surge""","b""No Help Mexico Kidnapping Surge",0.4019,11432.089844,11759.959961,11388.040039,11734.320312,212830000,11734.320312

In [39]:
averaged_score_df = score_df.groupby('Date')['Sentiment_score'].mean().reset_index()

In [40]:
merged_df  = pd.merge(averaged_score_df,index_df,on='Date',how = 'inner')

In [24]:
pip install plotly

Collecting plotly
  Downloading plotly-5.24.1-py3-none-any.whl (19.1 MB)
     --------------------------------------- 19.1/19.1 MB 43.5 MB/s eta 0:00:00
Collecting tenacity>=6.2.0
  Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Requirement already satisfied: packaging in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages (from plotly) (24.1)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.24.1 tenacity-9.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [42]:
fig = make_subplots(specs=[[{"secondary_y":True}]])
fig.add_trace(go.Candlestick(x=merged_df['Date'],
        open = merged_df['Open'],
        high = merged_df['High'],
        low = merged_df['Low'], 
        close = merged_df['Close'],
        name = "Price"),secondary_y = False)

In [43]:
fig.add_trace(go.Scatter(x=merged_df['Date'],y=merged_df['Sentiment_score'],name="Sentiment Score",line=dict(color='black',width=1)),secondary_y = True)

In [44]:
fig = go.Figure(data = go.Candlestick(x=merged_df['Date'],open = merged_df['Open'], high = merged_df['High'], low = merged_df['Low'], close = merged_df['Close']))

In [45]:
fig.update_layout(title = 'Interactive Chart for Index Price and Sentiment Score',yaxis_title = 'Price',xaxis_title='Date',xaxis_rangeslider_visible = True ,template = 'plotly_dark')

In [49]:
trace1 = go.Scatter(x=merged_df['Date'],y=merged_df['Close'], mode = 'lines+markers',name = 'Index Price',line = dict(color='blue'))
trace2 = go.Scatter(x=merged_df['Date'],y=merged_df['Sentiment_score'], mode = 'lines+markers',name = 'Sentiment Score',line = dict(color='green'))

layout = go.Layout(title = 'Index and sentiment score graph',xaxis = dict(title='Date'),yaxis = dict(title='Value'),hovermode = 'closest')

fig = go.Figure(data = [trace1],layout = layout)

fig.show()

In [50]:
trace1 = go.Scatter(x=merged_df['Date'],y=merged_df['Close'], mode = 'lines+markers',name = 'Index Price',line = dict(color='blue'))
trace2 = go.Scatter(x=merged_df['Date'],y=merged_df['Sentiment_score'], mode = 'lines+markers',name = 'Sentiment Score',line = dict(color='green'))

layout = go.Layout(title = 'Index and sentiment score graph',xaxis = dict(title='Date'),yaxis = dict(title='Value'),hovermode = 'closest')

fig = go.Figure(data = [trace2],layout = layout)

fig.show()